<?php

/**
 * PluginConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginConfiguration');
    }
}