<?php

/**
 * PluginProjectToProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProjectToProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProjectToProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProjectToProduct');
    }
}