<?php

/**
 * PluginTestEnvironmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTestEnvironmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTestEnvironmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTestEnvironment');
    }
}