<?php

/**
 * PluginProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trc
 * @subpackage model
 * @author     Julian Dumez <julianx.dumez@intel.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginProject extends BaseProject
{
}
