<?php

/**
 * PluginImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImage');
    }
}