<?php

/**
 * PluginComplementaryToolRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginComplementaryToolRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginComplementaryToolRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginComplementaryToolRelation');
    }
}