<?php

/**
 * PluginFileAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFileAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFileAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFileAttachment');
    }
}