<?php

/**
 * PluginDbInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDbInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDbInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDbInfo');
    }
}