<?php

/**
 * PluginTestSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTestSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTestSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTestSession');
    }
}