<?php

/**
 * PluginSearchTagRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSearchTagRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSearchTagRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSearchTagRelation');
    }
}