<?php

/**
 * PluginTableNameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTableNameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTableNameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTableName');
    }
}