<?php

/**
 * PluginMeasureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMeasureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMeasureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMeasure');
    }
}