<?php

/**
 * ComplementaryToolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplementaryToolTable extends PluginComplementaryToolTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplementaryToolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComplementaryTool');
    }
}