<?php

/**
 * ConfigurationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigurationTable extends PluginConfigurationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configuration');
    }

    /**
     * Get the configuration identifier for given environment and image identifiers.
     *
     * @param int $projectToProductId The relationship identifier of project group/project/product.
     * @param int $environmentId The environment identifier.
     * @param int $imageId The image identifier.
     *
     * @return The identifier of the configuration, or NULL.
     */
    public function getConfigurationId($projectToProductId, $environmentId, $imageId)
    {
    	$qa_generic = sfConfig::get("app_table_qa_generic");

    	$query = "SELECT c.id
    		FROM ".$qa_generic.".configuration c
    		WHERE c.project_to_product_id = ".$projectToProductId."
    			AND c.test_environment_id = ".$environmentId."
    			AND c.image_id = ".$imageId."";
    	$result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetch(PDO::FETCH_ASSOC);

    	if(!empty($result))
    		return $result["id"];

    	return null;
    }
}