<?php

/**
 * Configuration
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    trc
 * @subpackage model
 * @author     Julian Dumez <julianx.dumez@intel.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Configuration extends PluginConfiguration
{
	/**
	 * Delete a configuration (with image, test environment and reports).
	 *
	 * @return TRUE
	 */
	public function delete_configuration()
	{
		$qa_generic = sfConfig::get("app_table_qa_generic");

		$query = Doctrine_Manager::getInstance()->getCurrentConnection();

		$sql = "DELETE FROM ".$qa_generic.".test_session WHERE configuration_id = ".$this->getId();
		$result = $query->execute($sql);

		$query = Doctrine_Manager::getInstance()->getCurrentConnection();

		$sql = "DELETE FROM ".$qa_generic.".configuration WHERE id = ".$this->getId();
		$result = $query->execute($sql);

		return true;
	}
}
