<?php

/**
 * DbHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DbHistoryTable extends PluginDbHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DbHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DbHistory');
    }
}