<?php

/**
 * DbInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DbInfoTable extends PluginDbInfoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DbInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DbInfo');
    }
}