<?php

/**
 * MeasureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeasureTable extends PluginMeasureTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MeasureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Measure');
    }
}