<?php

/**
 * Project
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    trc
 * @subpackage model
 * @author     Julian Dumez <julianx.dumez@intel.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Project extends PluginProject
{
	/**
	 * Slugify the project name.
	 *
	 * @return The slugified name.
	 */
	public function getSlug()
	{
		return MiscUtils::slugify($this->getName());
	}

	public function getProjectGroup()
	{
		$qa_core = sfConfig::get("app_table_qa_core");
		$qa_generic = sfConfig::get("app_table_qa_generic");

		$query = "SELECT g.name
			FROM ".$qa_generic.".project p
			LEFT JOIN ".$qa_generic.".project_to_product ptp ON ptp.project_id = p.id
			LEFT JOIN ".$qa_core.".sf_guard_group g ON g.id = ptp.project_group_id
			WHERE p.id = ".$this->getId()."
			LIMIT 0,1";
		$result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetch(PDO::FETCH_ASSOC);

		return $result["name"];
	}

	/**
	 * Delete a project.
	 *
	 * @param $permanently TRUE to delete informations from database, FALSE to hide project.
	 *
	 * @return TRUE
	 */
	public function delete_project($permanently = false)
	{
		if($permanently == true)
		{
			// Not implemented yet
		}
		else
		{
			$this->setStatus(0);
			$this->save();
		}

		return true;
	}
}
