<?php

/**
 * ProjectToProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectToProductTable extends PluginProjectToProductTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectToProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectToProduct');
    }

    /**
     * Get the relationship identifier for given project group, project and product identifiers.
     *
     * @param int $projectGroupId The project group identifier.
     * @param int $projectId The project identifier.
     * @param int $productId The product identifier.
     *
     * @return The identifier of the relationship, or NULL.
     */
    public function getProjectToProductId($projectGroupId, $projectId, $productId)
    {
    	$qa_generic = sfConfig::get("app_table_qa_generic");

    	$query = "SELECT ptp.id
    		FROM ".$qa_generic.".project_to_product ptp
    		WHERE ptp.project_group_id = ".$projectGroupId."
    			AND ptp.project_id = ".$projectId."
    			AND ptp.product_id = ".$productId."";
    	$result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetch(PDO::FETCH_ASSOC);

    	if(!empty($result))
    		return $result["id"];

    	return null;
    }

    public function delete($id)
    {
        $qa_generic = sfConfig::get("app_table_qa_generic");

        $query = Doctrine_Manager::getInstance()->getCurrentConnection();
        $sql = "DELETE FROM ".$qa_generic.".project_to_product WHERE id = ".$id;
        $result = $query->execute($sql);
    }
}