<?php

/**
 * SearchTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SearchTagTable extends PluginSearchTagTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SearchTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SearchTag');
    }
}