<?php

/**
 * SearchTagRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SearchTagRelationTable extends PluginSearchTagRelationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SearchTagRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SearchTagRelation');
    }
}