<?php

/**
 * sfGuardUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    /**
     * Get list of users' profiles.
     *
     * @return
     */
    public function getUserProfiles()
    {
        $qa_core = sfConfig::get("app_table_qa_core");
        $query = "SELECT p.token, p.security_level FROM ".$qa_core.".sf_guard_user u
            JOIN ".$qa_core.".sf_guard_user_profile p ON p.user_id = u.id";
        $result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetchAll(PDO::FETCH_ASSOC);

        return $result;
    }

    /**
     * TODO
     * return
     */
    public function getIdList()
    {
    	$qa_core = sfConfig::get("app_table_qa_core");

    	$query = "SELECT u.id, u.username
			FROM ".$qa_core.".sf_guard_user u
			ORDER BY u.username ASC";
    	$result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetchAll(PDO::FETCH_ASSOC);

    	return $result;
    }
}