<?php

/**
 * sfGuardGroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object sfGuardGroupTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('sfGuardGroup');
	}

	/**
	 * Get the project group id corresponding to the given project group name.
	 *
	 * @param string $projectGroupName The project group name.
	 *
	 * @return The project group id or NULL.
	 */
	public function getProjectGroupId($projectGroupName)
	{
		$qa_core = sfConfig::get("app_table_qa_core");

		$query = "SELECT gg.id FROM ".$qa_core.".sf_guard_group gg WHERE gg.name = '".$projectGroupName."'";
		$result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetch(PDO::FETCH_ASSOC);

		if(!empty($result))
			return $result["id"];

		return null;
	}
	
	/**
	 * TODO
	 * @return 
	 */
	public function getBasicProjectGroups()
	{
		$qa_core = sfConfig::get("app_table_qa_core");
	
		$query = "SELECT pg.id, pg.name
			FROM ".$qa_core.".sf_guard_group pg
			ORDER BY pg.name ASC";
		$result = Doctrine_Manager::getInstance()->getCurrentConnection()->execute($query)->fetchAll(PDO::FETCH_ASSOC);
	
		return $result;
	}
}
