<?php

/**
 * TableNameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TableNameTable extends PluginTableNameTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TableNameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TableName');
    }
}