<?php

/**
 * TestResult
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    trc
 * @subpackage model
 * @author     Julian Dumez <julianx.dumez@intel.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TestResult extends PluginTestResult
{
	public function getFeature()
	{
		$tableName = Doctrine_Core::getTable("TableName")->findOneByName("test_result");

		$feature = Doctrine_Core::getTable("ComplementaryToolRelation")
			->createQuery()
			->where("table_name_id = ?", $tableName->getId())
			->andWhere("table_entry_id = ?", $this->getId())
			->execute();

		return $feature[0];
	}

	public function getPreviousResult($sessionId)
	{
		$qa_generic = sfConfig::get("app_table_qa_generic");

		$tableName = Doctrine_Core::getTable("TableName")->findOneByName("test_result");

		$query = Doctrine_Manager::getInstance()->getCurrentConnection();
		$result = $query->execute("
			SELECT * FROM ".$qa_generic.".test_result tr
				JOIN ".$qa_generic.".complementary_tool_relation ctr ON ctr.table_entry_id = tr.id
			WHERE ctr.table_name_id = ".$tableName->getId()."
				AND tr.test_session_id = ".$sessionId."
				AND tr.name = '".$this->getName()."'
		");
		$array = $result->fetchAll();

		if(count($array) > 0)
		{
			$testResult = new TestResult();
			$testResult->fromArray($array[0]);
			return $testResult;
		}

		return null;
	}
}
