<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SearchTagRelation', 'qa_generic');

/**
 * BaseSearchTagRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $table_name_id
 * @property integer $table_entry_id
 * @property integer $search_tag_id
 * @property TableName $TableName
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method integer           getTableNameId()    Returns the current record's "table_name_id" value
 * @method integer           getTableEntryId()   Returns the current record's "table_entry_id" value
 * @method integer           getSearchTagId()    Returns the current record's "search_tag_id" value
 * @method TableName         getTableName()      Returns the current record's "TableName" value
 * @method SearchTagRelation setId()             Sets the current record's "id" value
 * @method SearchTagRelation setTableNameId()    Sets the current record's "table_name_id" value
 * @method SearchTagRelation setTableEntryId()   Sets the current record's "table_entry_id" value
 * @method SearchTagRelation setSearchTagId()    Sets the current record's "search_tag_id" value
 * @method SearchTagRelation setTableName()      Sets the current record's "TableName" value
 * 
 * @package    trc
 * @subpackage model
 * @author     Julian Dumez <julianx.dumez@intel.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSearchTagRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('search_tag_relation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('table_name_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('table_entry_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('search_tag_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_search_tag_relation_table_name1', array(
             'fields' => 
             array(
              0 => 'table_name_id',
             ),
             ));
        $this->index('idx_search_tag_relation_table_entry_id', array(
             'fields' => 
             array(
              0 => 'table_entry_id',
             ),
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TableName', array(
             'local' => 'table_name_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
    }
}