<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DecisionCriteria', 'qa_core');

/**
 * BaseDecisionCriteria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property text $sql_request
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method string           getName()        Returns the current record's "name" value
 * @method string           getDescription() Returns the current record's "description" value
 * @method text             getSqlRequest()  Returns the current record's "sql_request" value
 * @method DecisionCriteria setId()          Sets the current record's "id" value
 * @method DecisionCriteria setName()        Sets the current record's "name" value
 * @method DecisionCriteria setDescription() Sets the current record's "description" value
 * @method DecisionCriteria setSqlRequest()  Sets the current record's "sql_request" value
 * 
 * @package    trc
 * @subpackage model
 * @author     Julian Dumez <julianx.dumez@intel.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDecisionCriteria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('decision_criteria');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('description', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('sql_request', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}