<?php

/**
 * PluginDbHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDbHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDbHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDbHistory');
    }
}