<?php

/**
 * PluginProductTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductType');
    }
}