<?php

/**
 * PluginDecisionCriteriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDecisionCriteriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDecisionCriteriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDecisionCriteria');
    }
}