<?php

/**
 * PluginSearchTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSearchTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSearchTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSearchTag');
    }
}